name = "edgestatus"
main = "./src/index.ts"
compatibility_date = "2023-10-16"
workers_dev = true
minify = false
# node_compat = true
send_metrics = false
logpush = false
kv_namespaces = [
  { binding = "CLOUDFLARE_KV_NAME", id = "CLOUDFLARE_KV_ID" }
]


# [triggers]
# crons = ["0 */5 * * *"]